### ISSUE TITLE
zipfile 

### ISSUE THREAD

**Issue by Emveez** [szymonmaszke/torchlambda#7]
`torchlambda:: Started packing Torchscript model to /home/user/DEV_WD/aws-lambda-torch/model_simulation/model.zip.
Traceback (most recent call last):
  File "/home/user/.local/bin/torchlambda", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/torchlambda/main.py", line 21, in main
    module.run(args)
  File "/home/user/.local/lib/python3.6/site-packages/torchlambda/subcommands/layer.py", line 18, in run
    args.compression, args.compression_level
TypeError: __init__() got an unexpected keyword argument 'compresslevel'
`
Running on ubuntu 18 and python 3.6. Is this due to wrong zipfile version??

**Comment by Emveez** [comment]
Seems that compresslevel is a featured added at python 3.7

**Comment by Emveez** [comment]
Using python 3.7 fix this
